# Generated by Django 5.2.1 on 2025-05-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_no', models.CharField(max_length=50)),
                ('implants_name', models.TextField()),
                ('implants_type', models.CharField(choices=[('SS', 'SS'), ('Titanium', 'Titanium'), ('Neither', 'Neither')])),
                ('size', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('assigned', models.CharField(choices=[('Santosh', 'Santosh'), ('Shiva', 'Shiva'), ('Neither', 'Neither')], max_length=10)),
                ('institute', models.CharField(max_length=100)),
                ('surgeon', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
